### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by EvanSong77** [unikcc/DiaASQ#5]
I am very interested in your work, when will the dataset be made public?

**Comment by EvanSong77** [comment]
> I am very interested in your work, when will the dataset be made public?
If possible can you send it to my email? My email is codewen77@163.com. Thanks!

**Comment by unikcc** [comment]
Thank you for your attention. We have now posted this dataset for NLPCC 2023 shared task 4 ([link](http://tcci.ccf.org.cn/conference/2023/cfpt.php)). Welcome to participate in the shared task to access the dataset. Alternatively, the dataset will also be released on this repository after the shared task period.
