### ISSUE TITLE
triplets组成

### ISSUE THREAD

**Issue by lxianl455** [unikcc/DiaASQ#8]
我想问问triplets中的组成是什么含义：
![image](https://github.com/unikcc/DiaASQ/assets/63391363/77dd9cac-cb6c-448e-9017-3d92e15c6dfe)
![image](https://github.com/unikcc/DiaASQ/assets/63391363/83d1fe14-d709-452c-8115-ff2a2499d66b)
为什么第一个会没有情感标签

**Comment by unikcc** [comment]
在三元组中存在Opinion的情况下，才有情感倾向，从而具有情感标签；这个例子只有Target和Aspect，只能算是一个pair，没有情感标签。

**Comment by lxianl455** [comment]
那为什么要放在triplets里面？还是说这种没有情感的都是算做pair，在测试四元组生成的时候不考虑的？

**Comment by unikcc** [comment]
这个初衷是为了标注的完整性，也方便模型预测。
从完整性上说，只看Target和Aspect Pair的话，可以算作一个独立的子任务。
从模型上来说，目前我们的模型是基于pair的，train1：小米的屏幕是京东方的；test1：小米的屏幕不错。如果train1中的（小米，屏幕）不被标注为一对，那么test1中的（小米，屏幕）可能也不会被识别为一对，从而影响真正的三元组的预测效果。

**Comment by lxianl455** [comment]
这种没有表示情感的，是不是也可以认为是neutral?
还有你们论文中报告的四元组预测的结果，有没有考虑这种作为一个四元组?

**Comment by unikcc** [comment]
至于为什么放在triplet里，主要为了方便；这种格式设计的triplet可以兼容pair和triplet；
这种算pair，不算四元组，所以没有情感极性一说。
评估四元组的时候，只考虑完整的四元组，不考虑这种情况。

**Comment by lxianl455** [comment]
还有就是评估四元组的时候，有一些四元组是没有Aspect，请问这种在评估的时候算一个完整的四元组吗？
比如这种：
![image](https://github.com/unikcc/DiaASQ/assets/63391363/b2789ff7-1a5d-4f04-bd97-80a4a8678391)

**Comment by unikcc** [comment]
不算。评估四元组的时候，**只考虑完整的四元组**，不考虑这种情况。

**Comment by lxianl455** [comment]
好的，谢谢你的耐心回答

**Comment by unikcc** [comment]
不客气，感谢关注

**Comment by lxianl455** [comment]
你们做test的时候也是可以用Replies 和 Speakers信息吗

**Comment by unikcc** [comment]
可以用

**Comment by lxianl455** [comment]
那关于那个完整的四元组，我代码数据分析出来，好像有531个完整的四元组，具体来说是这个数字吗，我不确定我数据处理的时候有没有错误。

**Comment by unikcc** [comment]
统计数据可以和论文对比；我们也提供了数据处理代码。

**Comment by unikcc** [comment]
以上这些问题的答案在论文和代码里都有，如有疑问可直接查询相关细节
